### ISSUE TITLE
Collection selector

### ISSUE THREAD

**Issue by SergeyTeplyakov** [nightroman/PowerShellTraps#4]
This is a relatively simple trap, but I've got into it recently.

Suppose you have a collection of custom objects:

``` powershell
$customers = 1..10 | foreach { [pscustomobject]@{Id= $_; Name = "CustomName($)"}}
```

Now, let suppose you want to iterate over each element and perform some computation:

``` powershell
foreach($customer in $customers)
{
    if ($customers.Id -eq 2)
    {
        Write-Host "Yep, Found customer with Id == 2"
    }
}
```

What do you expect?

I've made an error in the script, and now instead of getting "Yep, Found customer with Id == 2" only once I'll get this message as many times as a number of items in `$customers` variable.

Powershell has build-in feature for getting projections from the collection. This means that if collection `customers` has an objects with `Id` property, than `$customers.Id` will return an array with `Id` properties from each element.

And due collections equality trap `$customers.Id -eq 2` will always produce a sequence with one element that convertible to `$True`.

Unfortunately, I don't know the workaround for this trap, because this code is 100% legit. Even turning strict mode will not help.

**Comment by nightroman** [comment]
Yes, this should be in the list. I have been trapped by this feature, too. Not even because of typos. E.g. I expect a variable `$x` to be a scalar with some property `Prop` and I check this property as `$x.Prop -eq 42`. If something goes not as expected `$x` may be a collection instead of expected scalar. In this case in v2 `$x.Prop -eq 42` gives either false or error in the strict mode. In v3 `$x.Prop` is a collection of values, one of them is 42, so my check gives true as if all is "fine". But I did not expect `$x` to  be a collection. I.e. v2 helps me to reveal some unexpected issues earlier. v3 rather hides them at this point.

**Comment by nightroman** [comment]
For my use case at least there is a workaround. The check should be done as `42 -eq $x.Prop`. Then it will not be evaluated to true if `$x` is a collection.

**Comment by nightroman** [comment]
Pushed as [Collection-property-enumeration](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Collection-property-enumeration). Please close the issue if it looks good.

Later on I am going to add one more test case which shows how the typical "unexpected output" trap is combined with this one.
